feat: redirect to spanish news to espanol/cursos
freeCodeCamp/nginx-config pull request #20
Opened 2020-11-24 11:55 UTC by ahmadabdolsaheb

2020-11-24 11:57 UTC, ahmadabdolsaheb commented
@ojeytonwilliams could you take a look? thanks

2020-11-24 17:01 UTC, ojeytonwilliams requested changes

2020-11-24 17:25 UTC, ahmadabdolsaheb commented on sites-enabled/10-www.freecodecamp.org.conf
> +  location ~^/spanish/(.*)$ {
Thanks for catching this.

2020-11-24 17:25 UTC, ahmadabdolsaheb commented on sites-enabled/10-www.freecodecamp.org.conf
> +  location ~^/espanol/news/(.*)$ {
same as above.

2020-11-24 17:28 UTC, ahmadabdolsaheb commented on sites-enabled/10-www.freecodecamp.org.conf
> +    return 302 https://www.freecodecamp.org/espanol/cursos/$1;
I will double check with Quincy on this.

2020-11-25 08:42 UTC, closed without merging

2020-11-25 08:46 UTC, ahmadabdolsaheb commented
Thanks for the review. I am closing this since it will lead to complexity, and I will open another one for fixing the spanish -> espanol redirect.